config/routes.rb
Rails.application.routes.draw do
  

  # resources :admin do
  #   # get :make_moderator
  #   # get :make_normal_user
  #   delete 'admin/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  #   get 'admin/:id' => 'staff#show', as: :admin
  # end
  get 'staff/index'
  get 'staff/' => 'staff#index'
  get 'staff/:id' => 'staff#show', as: :admin

  get 'staff/show'

  resources :centers
  get 'dashboard', :to => 'dashboard#index'

  resources :available_times
  resources :programs do
    resources :available_times
  end
  resources :clients
  resources :bookings
  resources :sms
  devise_for :admins

  namespace :api do
    namespace :v1 do
      get '/sms', :to => 'sms#create'
      post '/sms', :to => 'sms#create'
      # resources :sms, only: [:create]
      # get '/drivers/tuktuk_drivers'
      # get '/drivers/bajaj_drivers'
    end
  end

  authenticated :admin do
    root 'admin/dashboard#index', as: :authenticated_admin
  end

   devise_scope :admin do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
  end

  resources :connections

  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
# == Schema Information
#
# Table name: programs
#
#  id              :integer          not null, primary key
#  name            :string
#  description     :text
#  sms_description :string
#  parallel        :boolean          default(FALSE)
#  fixed           :boolean          default(FALSE)
#  confirmation    :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  duration        :integer          default(50)
#  code            :string
#  color           :string
#  participants    :integer          default(1), not null
#

class Program < ApplicationRecord

	before_save { |program| 
		program.name.nil? ?    program.name : program.name = program.name.downcase 
		program.description.nil? ?  program.description : program.description = program.description.downcase 
		program.sms_description.nil? ?   program.sms_description : program.sms_description = program.sms_description.downcase  }

	validates_presence_of :code, :name, :description
	validates_uniqueness_of  :code, :color
 
	has_many :available_times
	has_many :bookings
	has_many :sms


	def duration_in_seconds
		self.duration * 60
	end

# 	max bookings per day
	def max_sessions day
		# return the number of people allowed to book per day
		available_times_for_this_day = self.available_times.where(day: day)

		total_session_time = 0
		if available_times_for_this_day.count > 0
			available_times_for_this_day.each do |val|
				time_in_seconds = val.end_time - val.start_time
				total_session_time += time_in_seconds
			end

			total_session_time_in_minutes = total_session_time/60
			max_bookings = total_session_time_in_minutes / self.duration

			return max_bookings.to_i
		else
			return total_session_time
		end

	end

	def max_participants_per_session
		return self.participants
	end

	def max_bookings day
		# total number if clients that can book this program in a particular session on this day
		max_participants_per_session
	end

	def week_max_bookings
		all_days = self.days

		total = 0

		all_days.each do |day|
			total += max_sessions day
		end

		return total
	end

	def sessions

		days = []
		times = []
		sessions = {}

		self.available_times.each do |time|
			# days << time.day
			# times << time.time
			 if sessions.key?(time.day)
			 	sessions[time.day] << ", #{time.time}"
			 else
				sessions[time.day] = time.time
			end
		end
		# hash = Hash[*days.zip(times).flatten]
		# return hash
		return sessions		
	end

# 	revise this to inlude double monday or tuesdays etc 
	def sessions_for_day day
		time = self.available_times.where(day: day)
		
		times = []
		if time.present?
			time.each do |t| 
			 times << t.time
			end
			return times
		else
			return false
		end
	end



	def days
		days = []

		self.available_times.each do |time|
			days << time.day.strip
		end

		return days
	end

	def times
		times = []

		self.available_times.each do |time|
			times << time.time
		end

		return times
	end

	def latest_booking_times

		sessions = {}

		self.available_times.each do |avail|
			if sessions.key?(avail.day)
				sessions[avail.day] << ", #{avail.latest_booking_time}"
			else
				sessions[avail.day] = avail.latest_booking_time
			end
		end

		return sessions #{"Friday"=>"11:10 AM", "Monday"=>"03:10 PM"} 
		
	end

	def get_starting_times_for_sessions
		session_times = self.sessions

		starting_times_for_each_session = {}#this week
		last_booking_times              = self.latest_booking_times

		session_times.each do |sess|
			# sess {"Monday"=>"06:00 AM - 07:00 AM, 06:00 PM - 07:00 PM"} 
			no_of_start_times = self.max_sessions(sess[0]) 

			start_end_times_list = sess[1].split(',') # result ::  ["06:00 AM - 07:00 AM", " 06:00 PM - 07:00 PM"]

			# start_end_times.size
			start_end_times_real = [] # this will hold the starting and ending times separated by commas
			i = 0
			while i < start_end_times_list.size
				start_end_times_real << start_end_times_list[i].split('-') # result::  [["06:00 AM ", " 07:00 AM"], [" 06:00 PM ", " 07:00 PM"]] 
				i = i + 1
			end	
			
			puts " STARTING TIMES real  #{ start_end_times_real}"
			# puts "Back to main loop ******"
			starting_times_for_each_session[sess[0]] = []#start_end_times_real[0][0]
			s = 0 #starting and ending times array counter
			j = 0 #no of booking times for particular day counter
			while s < start_end_times_real.size
				# get start times first.
				starting_times_for_each_session[sess[0]] << start_end_times_real[s][0]
				s = s + 1
			end
			while s < start_end_times_real.size
					
					while j < no_of_start_times
						# byebug
						# sometimes the j counter goes ahead, when a time  is not inserted into the hash, so we have to take it back by one when that happens
						puts " HERE IT IS #{ starting_times_for_each_session[sess[0]][j]}"
						# booking_time =  starting_times_for_each_session[sess[0]][j].nil?  ?  "#{(Time.zone.parse(starting_times_for_each_session[sess[0]][j-1]) + (self.duration * 60)).strftime("%I:%M %p")}"  : "#{(Time.zone.parse(starting_times_for_each_session[sess[0]][j]) + (self.duration * 60)).strftime("%I:%M %p")}"
						booking_time =  starting_times_for_each_session[sess[s]][j].nil?  ?  "#{(Time.zone.parse(starting_times_for_each_session[sess[s]][j-1]) + (self.duration * 60)).strftime("%I:%M %p")}"  : "#{(Time.zone.parse(starting_times_for_each_session[sess[s]][j]) + (self.duration * 60)).strftime("%I:%M %p")}"
						
						latest_time_to_book = last_booking_times[sess[0]]
						# puts "last booking #{latest_time_to_book} "
						# puts "booking #{latest_time_to_book} "
						if Time.zone.parse(booking_time) <=  Time.zone.parse(latest_time_to_book)
							starting_times_for_each_session[sess[0]] <<  (Time.zone.parse(starting_times_for_each_session[sess[0]][j]) + (self.duration * 60)).strftime("%I:%M %p")  #2nd start time
						end

						j += 1						
					end
				s = s + 1
			end			
		end
		
		return starting_times_for_each_session
	end


	# returns starting times with dates for this whole week regardless of when you are querying
	# that means, when you query on Friday you will get results for the past monday not the next.
	def get_times_and_dates
		starting_times_without_dates = self.get_starting_times_for_sessions

		arr_of_dated_days 	= []

		# collect all keys so that I can modify and add date
		starting_times_without_dates.keys.each { |key|  arr_of_dated_days << key }

		
		# add date to day now
		arr_of_dated_days.collect! do |day|
			date 		= (self.get_date_for day).day #if I want next week's dates, this is where I need to change, get_date_for to get_date_for_next_week
			dated_day 	= day + ' ' + date.to_s

			# replace the array value
			day = dated_day
		end

		# loop through the dated array
		arr_of_dated_days.each do |dated_day|
			# get the hash keys to search through 
			starting_times_without_dates.keys.select {    |key| 
				# replace with the new dated days
				if key.include?(dated_day.split[0])
					hash_key_to_alter = key
					starting_times_without_dates[dated_day] = starting_times_without_dates.delete(hash_key_to_alter)
				end
			}
		end

		return starting_times_without_dates  
	end

	# get tomorrow and future dates, excludin past days' dates
	def get_only_future_days
		starting_times_without_dates = self.get_starting_times_for_sessions

		arr_of_dated_days 	= []

		# collect all keys so that I can modify and add date
		starting_times_without_dates.keys.each { |key|  arr_of_dated_days << key }

		
		# add date to day now
		arr_of_dated_days.collect! do |day|
			date        = Date.today >= self.get_date_for(day) ? (self.get_date_for_next_week day).day : (self.get_date_for day).day #get next weeks dates only
			dated_day 	= day + ' ' + date.to_s

			# replace the array value
			day = dated_day
		end

		# loop through the dated array
		arr_of_dated_days.each do |dated_day|
			# get the hash keys to search through 
			starting_times_without_dates.keys.select {    |key| 
				# replace with the new dated days
				if key.include?(dated_day.split[0])
					hash_key_to_alter = key
					starting_times_without_dates[dated_day] = starting_times_without_dates.delete(hash_key_to_alter)
				end
			}
		end

		return starting_times_without_dates  
	end

	# returns only next weeks dates
	def get_only_next_weeks_dates
		starting_times_without_dates = self.get_starting_times_for_sessions

		arr_of_dated_days 	= []

		# collect all keys so that I can modify and add date
		starting_times_without_dates.keys.each { |key|  arr_of_dated_days << key }

		
		# add date to day now
		arr_of_dated_days.collect! do |day|
			date        = (self.get_date_for_next_week day).day #get next weeks dates only
			dated_day 	= day + ' ' + date.to_s

			# replace the array value
			day = dated_day
		end

		# loop through the dated array
		arr_of_dated_days.each do |dated_day|
			# get the hash keys to search through 
			starting_times_without_dates.keys.select {    |key| 
				# replace with the new dated days
				if key.include?(dated_day.split[0])
					hash_key_to_alter = key
					starting_times_without_dates[dated_day] = starting_times_without_dates.delete(hash_key_to_alter)
				end
			}
		end

		return starting_times_without_dates  
	end

	# this week
	def get_date_for day
		days = { "Monday" => 1 , "Tuesday" => 2 ,  "Wednesday" => 3 , "Thursday" => 4 , "Friday" => 5 }

		diff = days[day] - Date.today.wday
		date = advance_date diff
		return date
	end

	# next week
	def get_date_for_next_week day
		days = { "Monday" => 0 , "Tuesday" => 1 ,  "Wedneday" => 2, "Thursday" => 3 , "Friday" => 4 }

		diff = days[day] #- Date.today.wday
		date = next_week_advance_date diff
		return date
	end

private
	def advance_date diff
		return Date.today.advance(days: diff)
	end

	def next_week_advance_date day
		return Date.today.next_week.advance(days: day)
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @available_times  = @program.available_times.paginate(:page => params[:page], :per_page => 20)
    @today            = @program.bookings.where(created_at: Time.now.beginning_of_day..Time.now.end_of_day).count

  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to programs_url, notice: 'Program was successfully created.' }
        # format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :description, :sms_description, :parallel, :color, :code, :participants)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.haml
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        %h3.box-title Provide program details
      %form{:lpformnum => "1", :role => "form"}
      = simple_form_for @program do |f|
        - if @program.errors.any?
          #error_explanation
            %h2= "#{pluralize(@program.errors.count, "error")} prohibited this program from being saved:"
            %ul
              - @program.errors.full_messages.each do |message|
                %li= message
        %form{:_lpchecked => "1", :lpformnum => "1", :role => "form"}
          .box-body
            .row
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Program Name
                  / = f.label :name
                  = f.text_field :name, class: "form-control", placeholder: "Enter name"
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Description
                  = f.text_area :description, class: "form-control my-colorpicker1 colorpicker-element"
            .row
              .col-md-6
                .form-group
                  %label{:for => "exampleInputPassword1"} Select program color
                  -# = f.text_field :color, class: "form-control", placeholder: "pending, confirmed, cancelled"
                  -# %input.form-control.my-colorpicker1.colorpicker-element{:type => "text"}/
                  = f.text_field :color,  class: "form-control", placeholder: "Click here to see color pop up"
                .input-group-addon
                %i{:style => "background-color: rgb(6, 89, 29);"}
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Is it parallel?
                  %p
                  -# = f.label :name
                  -# = f.text_field :parallel, class: "form-control", placeholder: "Enter name"
                  = f.select :parallel, options_for_select([['True', true], ['False', false]])
            .row
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Max mumber of participants
                  / = f.label :name
                  = f.text_field :participants, class: "form-control", placeholder: "Enter a Number"
              .col-md-6
                .form-group
                  %label{:for => "exampleInputEmail1"} Program Code (For SMS booking)
                  / = f.label :name
                  = f.text_field :code, class: "form-control", placeholder: "Must be nuique ...B#"
          
            = f.button :submit, class: "btn btn-primary"

app/views/programs/_new.html.haml
#modal-default.modal.fade.in{:style => "display: block; padding-right: 10px;"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Default Modal
      .modal-body
        = render 'form'
    .modal-footer
        %button.btn.btn-default.pull-left{"data-dismiss" => "modal", :type => "button"} Close
     

app/views/programs/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Programs
        .box-tools.pull-right
          .digg_pagination
            = will_paginate programs 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 60px;", :tabindex => "0"} Program Name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Program code
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 60px;", :tabindex => "0"} Color
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "", :rowspan => "1", :style => "width: 70px;", :tabindex => "0"} Parallel?
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 113px;", :tabindex => "0"} Options
                %tbody
                  - programs.each do |program|

                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td= program.name
                      -#%td= program.description
                      -#%td= program.sms_description
                      %td= program.code
                      %td
                        %span.badge{:style => "background-color: #{program.color};"} #{program.color}
                      %td= program.parallel
                      / %td= voucher.year
                      %td 
                        -if current_admin && current_admin.is_moderator?
                          = link_to 'Show Details', program, class: "label label-warning"
                          = link_to 'Edit', edit_program_path(program), class: "label label-default"
                        -elsif current_admin && current_admin.is_admin?
                          = link_to 'Show Details', program, class: "label label-warning"
                          = link_to 'Edit', edit_program_path(program), class: "label label-default"
                          = link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} Program Name
                    %th{:colspan => "1", :rowspan => "1"} Program code
                    %th{:colspan => "1", :rowspan => "1"} Color
                    %th{:colspan => "1", :rowspan => "1"} Parallel?
                    %th{:colspan => "1", :rowspan => "1"} Options

          .row
            .col-sm-5
              .page_info
                = page_entries_info programs
            .col-sm-7
              .digg_pagination
                = will_paginate programs 
      / /.box-body
    / /.box
  / /.col

app/views/programs/edit.html.haml
%h1 Editing program

= render 'form'

= link_to 'Show Details', @program , class: "btn btn-default"
\|
= link_to 'Back', programs_path, class: "btn btn-default"

app/views/programs/index.html.haml
%section.content-header
  %h1
    Lishe Leo Programs
    %small All Programs in the database
  %ol.breadcrumb
    %li
      %a{:href => "#"}
        %i.fa.fa-dashboard
        Level
    %li.active Here


%br


%br
#partial_page
  =render "programs/table", programs: @programs #the table that was previously here was extracted to the partial to be DRY. seems like I needed it more than I thought! :-)

%br
-if current_admin && current_admin.is_previlaged?
  %p= link_to 'New Program', new_program_path, class: "btn btn-primary" #, :remote => true, 'data-toggle' =>  "modal", class: "btn btn-primary"

app/views/programs/new.html.haml
%h1 New program

= render 'form'

= link_to 'Back', programs_path, class: "btn btn-default"

app/views/programs/new.js.erb
$('.modal-default').html("<%= j render(partial: 'new') %>");

// $(function () {
//     console.log('COLOR PICKER MAIN');
//     $('.input-group-addon').colorpicker();
// });


$('#program_color').colorpicker().on('colorpickerChange', function (e) {
    // initialize the input on colorpicker creation
//    io.val(e.color.string());
//
//    io.on('change keyup', function () {
//        e.colorpicker.setValue(io.val());
//    });
    console.log('COLOR PICKER www');
})

 //$('#program_color').val( "llalala");

//colorpicker().on( 'colorpickerChange', function (event) {
//    console.log('COLOR PICKER EVENT ');
//        // $('.input-group-addon').css('background-color', event.color.toString());
//    console.log('COLOUR ' + event.colorpicker.picker.parents);
//    $('#program_color').val( "event.color.toString()");
//});
//$('.input-group-addon').on( function (event) {
//    console.log('COLOR PICKER EVENT ');
//        // $('.input-group-addon').css('background-color', event.color.toString());
//    console.log('COLOUR ' + event.colorpicker.picker.parents);
//    $('#program_color').val( "event.color.toString()");
//});

$('#modal-default').modal('show') 

app/views/programs/show.html.haml
-# %p#notice= notice

// %p
//   %b Name:
//   = @program.name
// %p
//   %b Description:
//   = @program.description
// %p
//   %b Sms description:
//   = @program.sms_description
// %p
//   %b Parallel:
//   = @program.parallel

.row
  .col-md-4.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-aqua
        %i.fa.fa-book
      .info-box-content
        %span.info-box-text Program
        %span.info-box-number #{@program.name.camelcase}
        %p #{@program.participants} participants per session
        %p #{@today} bookings today
      / /.info-box-content
    / /.info-box
  / /.col
  .col-md-4.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-green
        %i.fa.fa-flag-o
      .info-box-content
        %span.info-box-text
        %p #{ truncate(@program.description)}
        %span.info-box-number 410
      / /.info-box-content
    / /.info-box
  / /.col
  .col-md-4.col-sm-6.col-xs-12
    .info-box
      %span.info-box-icon.bg-yellow
        %i.fa.fa-files-o
      .info-box-content
        %span.info-box-text Can it Run parallel?
        %span.info-box-number #{@program.parallel}
      / /.info-box-content
    / /.info-box
  / /.col
  -# .col-md-3.col-sm-6.col-xs-12
  -#   .info-box
  -#     %span.info-box-icon.bg-red
  -#       %i.fa.fa-star-o
  -#     .info-box-content
  -#       %span.info-box-text Likes
  -#       %span.info-box-number 93,139
  -#     / /.info-box-content
  -#   / /.info-box
  -# / /.col


%br
#partial_page
  =render "available_times/table", available_times: @available_times


= link_to 'Back', programs_path, class: "btn btn-default"
\|
= link_to 'Edit Program', edit_program_path(@program), class: "btn btn-default"
\|
= link_to 'Add Available time', new_program_available_time_path(program_id: @program.id ), class: "btn btn-default"