config/routes.rb
Rails.application.routes.draw do
  

  # resources :admin do
  #   # get :make_moderator
  #   # get :make_normal_user
  #   delete 'admin/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  #   get 'admin/:id' => 'staff#show', as: :admin
  # end
  get 'staff/index'
  get 'staff/' => 'staff#index'
  get 'staff/:id' => 'staff#show', as: :admin

  get 'staff/show'

  resources :centers
  get 'dashboard', :to => 'dashboard#index'

  resources :available_times
  resources :programs do
    resources :available_times
  end
  resources :clients
  resources :bookings
  resources :sms
  devise_for :admins

  namespace :api do
    namespace :v1 do
      get '/sms', :to => 'sms#create'
      post '/sms', :to => 'sms#create'
      # resources :sms, only: [:create]
      # get '/drivers/tuktuk_drivers'
      # get '/drivers/bajaj_drivers'
    end
  end

  authenticated :admin do
    root 'admin/dashboard#index', as: :authenticated_admin
  end

   devise_scope :admin do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
  end

  resources :connections

  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/center.rb
# == Schema Information
#
# Table name: centers
#
#  id           :uuid             not null, primary key
#  name         :string
#  location     :string
#  phone_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Center < ApplicationRecord

    has_many :clients
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show, :edit, :update, :destroy]

  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
  end

  # GET /centers/new
  def new
    @center = Center.new
  end

  # GET /centers/1/edit
  def edit
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centers/1
  # PATCH/PUT /centers/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: 'Center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def center_params
      params.require(:center).permit(:name, :location, :phone_number)
    end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.haml
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        %h3.box-title Provide center details
      %form{:lpformnum => "1", :role => "form"}
      = simple_form_for @center, html: { multipart: true } do |f|
        - if @center.errors.any?
          #error_explanation
            %h2= "#{pluralize(@center.errors.count, "error")} prohibited this center from being saved:"
            %ul
              - @center.errors.full_messages.each do |message|
                %li= message
        %form{:_lpchecked => "1", :lpformnum => "1", :role => "form"}
          .box-body
            .row
              .col-md-3
                .form-group
                  %label{:for => "exampleInputEmail1"} Center Name
                  / = f.label :name
                  = f.text_field :name, class: "form-control", placeholder: "Enter Unique Name"
              .col-md-3
                .form-group
                  %label{:for => "exampleInputPassword1"} Where is it Located?
                  = f.text_field :location, class: "form-control", placeholder: "Enter Center Location"
              .col-md-3
                .form-group
                  %label{:for => "exampleInputPassword1"} Contact Number
                  = f.text_field :phone_number, class: "form-control", placeholder: "Enter Phone Number"
            .row

          / /.box-body
          .box-footer
            = f.submit class: "btn btn-primary"

app/views/centers/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Centers
        .box-tools.pull-right
          .digg_pagination
            = will_paginate centers 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Center Name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Location
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Contact
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 250px;", :tabindex => "0"} Options
                %tbody
                  - centers.each do |center|

                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td= center.name
                      %td= center.location
                      %td= center.phone_number
                      %td 
                        -if current_admin && current_admin.is_moderator?
                          = link_to 'Show Details', center, class: "label label-warning"
                          = link_to 'Edit', edit_center_path(center), class: "label label-default"
                        -elsif current_admin && current_admin.is_admin?
                          = link_to 'Show Details', center, class: "label label-warning"
                          = link_to 'Edit', edit_center_path(center), class: "label label-default"
                          = link_to 'Delete', center, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} Center Name
                    %th{:colspan => "1", :rowspan => "1"} Location
                    %th{:colspan => "1", :rowspan => "1"} Contact
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info centers
            .col-sm-7
              .digg_pagination
                = will_paginate centers 
      / /.box-body
    / /.box
  / /.col

app/views/centers/edit.html.haml
%h1 Editing center

= render 'form'


= link_to 'Show Details', @center, class: "btn btn-default"
\|
= link_to 'Back', centers_path, class: "btn btn-default"

app/views/centers/index.html.haml
%h1 Listing centers

#partial_page
  =render "centers/table", centers: @centers
%br

= link_to 'New Center', new_center_path, class: "btn btn-primary"

app/views/centers/new.html.haml
%h1 New center

= render 'form'

= link_to 'Back', centers_path, class: "btn btn-default"

app/views/centers/show.html.haml
%p#notice= notice


%p#notice= notice
.row
  .col-md-4
    .box.box-default
      .box-header.with-border
        %h3.box-title #{@center.name} 
        .box-tools.pull-right
          // %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
          //   %i.fa.fa-minus
        / /.box-tools
      / /.box-header
      .box-body
        = @center.location
        %ul.nav.nav-stacked
          %li
            %a{:href => "#"}
              Total Bookings
              %span.pull-right.badge.bg-blue 31
          %li
            %a{:href => "#"}
              Total Clients 
              %span.pull-right.badge.bg-aqua 5
          %li
            %a{:href => "#"}
              Completed Projects
              %span.pull-right.badge.bg-green 12
          -# %li
          -#   %a{:href => "#"}
          -#     Confirmation status
          -#     %span.pull-right.badge.bg-red #{@center.confirm_status}
      / /.box-body




-# %p
-#   %b Name:
-#   = @center.name
-# %p
-#   %b Location:
-#   = @center.location
-# %p
-#   %b Phone number:
-#   = @center.phone_number

= link_to 'Edit', edit_center_path(@center), class: "btn btn-default"
\|
= link_to 'Back', centers_path, class: "btn btn-default"