config/routes.rb
Rails.application.routes.draw do
  

  # resources :admin do
  #   # get :make_moderator
  #   # get :make_normal_user
  #   delete 'admin/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
  #   get 'admin/:id' => 'staff#show', as: :admin
  # end
  get 'staff/index'
  get 'staff/' => 'staff#index'
  get 'staff/:id' => 'staff#show', as: :admin

  get 'staff/show'

  resources :centers
  get 'dashboard', :to => 'dashboard#index'

  resources :available_times
  resources :programs do
    resources :available_times
  end
  resources :clients
  resources :bookings
  resources :sms
  devise_for :admins

  namespace :api do
    namespace :v1 do
      get '/sms', :to => 'sms#create'
      post '/sms', :to => 'sms#create'
      # resources :sms, only: [:create]
      # get '/drivers/tuktuk_drivers'
      # get '/drivers/bajaj_drivers'
    end
  end

  authenticated :admin do
    root 'admin/dashboard#index', as: :authenticated_admin
  end

   devise_scope :admin do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
  end

  resources :connections

  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/available_time.rb
# == Schema Information
#
# Table name: available_times
#
#  id         :integer          not null, primary key
#  day        :string
#  start_time :time
#  end_time   :time
#  program_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AvailableTime < ApplicationRecord
	belongs_to :program



	def time
		time = self.start_time.strftime("%I:%M %p")
		end_time = self.end_time.strftime("%I:%M %p")

		return time + ' - ' + end_time
	end

	# formated time
	def fstart_time
		self.start_time.strftime("%I:%M %p")
	end

	def fend_time
		self.start_time.strftime("%I:%M %p")
	end


	# returns ending time - program duration to make sure tht last booking does no ve a few minutes
	def latest_booking_time
		time = (self.end_time - self.program.duration_in_seconds).strftime("%I:%M %p")
		return time
	end
end

app/controllers/available_times_controller.rb
class AvailableTimesController < ApplicationController
  before_action :set_available_time, only: [:show, :edit, :update]

  # GET /available_times
  # GET /available_times.json
  def index
    @available_times = AvailableTime.all.paginate(:page => params[:page], :per_page => 20)
    # @program = @available_time.first.program
  end

  # GET /available_times/1
  # GET /available_times/1.json
  def show
  end

  # GET /available_times/new
  def new
    @available_time = AvailableTime.new
  end

  # GET /available_times/1/edit
  def edit
  end

  # POST /available_times
  # POST /available_times.json
  def create
    @available_time = AvailableTime.new(available_time_params)
    @program  = @available_time.program

    respond_to do |format|
      if @available_time.save
        # format.html { redirect_to available_times_url, notice: 'Available time was successfully created.' }
        format.html { redirect_to @program, notice: 'Available time was successfully created.' }
        format.json { render :show, status: :created, location: @available_time }
      else
        format.html { render :new }
        format.json { render json: @available_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_times/1
  # PATCH/PUT /available_times/1.json
  def update
    @program =  @available_time.program
    respond_to do |format|
      if @available_time.update(available_time_params)
        # format.html { redirect_to @available_time, notice: 'Available time was successfully updated.' }
        format.html { redirect_to @program, notice: 'Available time was successfully updated.' }
        format.json { render :show, status: :ok, location: @available_time }
      else
        format.html { render :edit }
        format.json { render json: @available_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_times/1
  # DELETE /available_times/1.json
  def destroy
    @available_time = AvailableTime.find(params[:id])
    @program =  @available_time.program
    @available_time.destroy
    respond_to do |format|
      format.html { redirect_to @program, notice: 'Available time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_time
      @available_time = AvailableTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def available_time_params
      params.require(:available_time).permit(:day, :start_time, :end_time, :program_id)
    end
end

app/helpers/available_times_helper.rb
module AvailableTimesHelper
end

app/views/available_times/_form.html.haml
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        %h3.box-title Provide available_time details
      %form{:lpformnum => "1", :role => "form"}
      = simple_form_for @available_time, html: { multipart: true } do |f|
        - if @available_time.errors.any?
          #error_explanation
            %h2= "#{pluralize(@available_time.errors.count, "error")} prohibited this available_time from being saved:"
            %ul
              - @available_time.errors.full_messages.each do |message|
                %li= message
        %form{:_lpchecked => "1", :lpformnum => "1", :role => "form"}
          .box-body
            -# %p Beginning and ending time of day are the office hours, excluding lunch  or break times.
            -# %p To h
            .row
              .col-md-3
                .form-group
                  %label{:for => "exampleInputEmail1"} Choose program
                  %p
                  = f.select :program_id, Program.all.map { |c| [c.name, c.id] }, include_blank: false, :selected => params[:program_id]
              .col-md-3
                .form-group
                  %label{:for => "exampleInputEmail1"} Choose a Day
                  %p
                  = f.select :day, options_for_select([['Monday', "Monday"], ['Tuesday', "Tuesday"], ['Wednesday', "Wednesday"], ['Thursday', "Thursday"], ['Friday', "Friday"]])
                  -# = f.text_field :day, class: "form-control", placeholder: "Enter Unique Name"
              .col-md-3
                .form-group
                  %label{:for => "exampleInputPassword1"} Beginning Time of Day (24h)
                  = f.input :start_time, class: "form-control", placeholder: "Enter a Starting time"
              .col-md-3
                .form-group
                  %label{:for => "exampleInputPassword1"} End Time of day  (24h)
                  = f.input :end_time, class: "form-control", placeholder: "Enter an Ending time"
            .row

          / /.box-body
          .box-footer
            = f.submit class: "btn btn-primary"

app/views/available_times/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Available Times for  #{  available_times.first.present? ? available_times.first.program.name.camelcase : " " }
        .box-tools.pull-right
          .digg_pagination
            = will_paginate available_times 
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            %br
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    -# %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 182px;", :tabindex => "0"} Prgram Name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Day
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Start Time
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} End Time
                    
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 250px;", :tabindex => "0"} Options
                %tbody
                  - available_times.each do |available_time|

                    %tr{:class => "#{cycle('even', 'odd')}"}
                      -# %td.sorting_1=  available_time.program.name #strftime("%I:%M%p")
                      %td= available_time.day
                      %td= available_time.start_time.strftime("%I:%M%p")
                      %td= available_time.end_time.strftime("%I:%M%p")
                      %td 
                        -if current_admin && current_admin.is_moderator?
                          -# = link_to 'Show Details', available_time, class: "label label-warning"
                          = link_to 'Edit', edit_program_available_time_path(available_time ,program_id: @program.id ), class: "label label-default"
                         
                          -# = link_to 'Edit', edit_admin_establishment_path(establishment), class: "label label-default"
                          -# = link_to "Details", admin_establishment_path(establishment), class: "label label-warning"                         
                          -# = link_to "Images", admin_establishment_pictures_path(establishment), class: "label label-success"
                        -elsif current_admin && current_admin.is_admin?
                          -# = link_to 'Show Details', available_time, class: "label label-warning"
                          = link_to 'Edit', edit_program_available_time_path(available_time ,program_id: @program.id ), class: "label label-default"
                          = link_to 'Destroy', available_time, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    -# %th{:colspan => "1", :rowspan => "1"} Program Name
                    %th{:colspan => "1", :rowspan => "1"} Day
                    %th{:colspan => "1", :rowspan => "1"} Start Time
                    %th{:colspan => "1", :rowspan => "1"} End time
                    
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info available_times
            .col-sm-7
              .digg_pagination
                = will_paginate available_times 
      / /.box-body
    / /.box
  / /.col

app/views/available_times/edit.html.haml
%h1 Editing available_time

= render 'form'

= link_to 'Show Details', @available_time, class: "btn btn-default"
\|
= link_to 'Back', available_times_path, class: "btn btn-default"

app/views/available_times/index.html.haml
%h1 Listing Available Times for Programs

%br
#partial_page
  =render "available_times/table", available_times: @available_times

= link_to 'New Available time', new_available_time_path,  class: "btn btn-primary"

app/views/available_times/new.html.haml
%h1 New Program Availability time

= render 'form'

= link_to 'Back', available_times_path, class: "btn btn-default"

app/views/available_times/show.html.haml
%p#notice= notice

%p
  %b Day:
  = @available_time.day
%p
  %b Start time:
  = @available_time.start_time
%p
  %b End time:
  = @available_time.end_time

= link_to 'Edit', edit_available_time_path(@available_time)
\|
= link_to 'Back', available_times_path